// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVR5UDbAXaOU9irpdlW9HcSloRuz4eI_Y',
    appId: '1:898488212654:web:0bd7ea3002ad8407c9e13f',
    messagingSenderId: '898488212654',
    projectId: 'food-ordering-8db',
    authDomain: 'food-ordering-8db.firebaseapp.com',
    storageBucket: 'food-ordering-8db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-QzYKWXEZE83Jxo8PryIaofC5uM-4sQ',
    appId: '1:898488212654:android:573958198ecf2a33c9e13f',
    messagingSenderId: '898488212654',
    projectId: 'food-ordering-8db',
    storageBucket: 'food-ordering-8db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldMiK9wayAZ-lPny-C8Z9mv5UtVZelio',
    appId: '1:898488212654:ios:950ef68d68c8fa1dc9e13f',
    messagingSenderId: '898488212654',
    projectId: 'food-ordering-8db',
    storageBucket: 'food-ordering-8db.appspot.com',
    iosBundleId: 'com.example.foodOrderingGta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldMiK9wayAZ-lPny-C8Z9mv5UtVZelio',
    appId: '1:898488212654:ios:a298fe5235d8ab09c9e13f',
    messagingSenderId: '898488212654',
    projectId: 'food-ordering-8db',
    storageBucket: 'food-ordering-8db.appspot.com',
    iosBundleId: 'com.example.foodOrderingGta.RunnerTests',
  );
}
